/* USER TABLE INIT */
DROP TABLE IF EXISTS USER;

CREATE TABLE USER(USER_ID  INT AUTO_INCREMENT PRIMARY KEY, EMAIL VARCHAR(255), PASSWORD VARCHAR(255), USER_NAME VARCHAR(255), 
	COUNTRY VARCHAR(255));

INSERT INTO USER VALUES(1, 'ibarra@hotmail.fr', 'pwd', 'Alcatraz', 'France');
INSERT INTO USER VALUES(2, 'idobi@hotmail.fr', 'pwd', 'Damien', 'France');
INSERT INTO USER VALUES(3, 'coco@gmail.com', 'pwd', 'Coco', 'Belgium');

SELECT * FROM USER ORDER BY USER_ID;

/* ALBUM_COLLECTED TABLE INIT */
DROP TABLE IF EXISTS ALBUM_COLLECTED;

CREATE TABLE ALBUM_COLLECTED(ALBUM_COLLECTED_ID INT AUTO_INCREMENT PRIMARY KEY, USER_ID INT, ALBUM_ID INT);

INSERT INTO ALBUM_COLLECTED VALUES(1, 1, 1);
INSERT INTO ALBUM_COLLECTED VALUES(2, 1, 2);
INSERT INTO ALBUM_COLLECTED VALUES(3, 1, 3);

SELECT * FROM ALBUM_COLLECTED;

/* ALBUM TABLE INIT */
DROP TABLE IF EXISTS ALBUM;

CREATE TABLE ALBUM(ALBUM_ID INT AUTO_INCREMENT PRIMARY KEY, ALBUM_NAME VARCHAR(255), ARTIST_NAME VARCHAR(255),
	RELEASE_DATE TIMESTAMP, ALBUM_FORMAT VARCHAR(255));

INSERT INTO ALBUM VALUES(1, 'The Wreck Age: I-Face To Faith', 'Crackmind', '2017-01-17', 'LP');
INSERT INTO ALBUM VALUES(2, 'The Wreck Age: II-Dark Side Of The Mind', 'Crackmind', '2018-09-01', 'LP');
INSERT INTO ALBUM VALUES(3, 'The Wreck Age: III-Vertigo Of The Fragile', 'Crackmind', '2019-11-12', 'LP');

SELECT * FROM ALBUM;